# Generated by Django 3.2 on 2021-05-04 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('finished', models.BooleanField(default=False, verbose_name='Сделан')),
            ],
            options={
                'verbose_name': 'Чеклист',
                'verbose_name_plural': 'Чеклисты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[(0, 'PLANNING'), (1, 'ACTIVE'), (2, 'IN_CONTROL'), (3, 'FINISHED')], max_length=10, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Время начала')),
                ('finish_date', models.DateField(verbose_name='Время завершения')),
                ('possible_finish_date', models.DateField(verbose_name='Планируемое время завершения')),
                ('checklists', models.ManyToManyField(blank=True, to='core.CheckList', verbose_name='Чеклисты')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('observers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[(0, 'PLANNING'), (1, 'ACTIVE'), (2, 'IN_CONTROL'), (3, 'FINISHED')], max_length=10, verbose_name='Название')),
                ('current_status', models.CharField(choices=[(0, 'PLANNING'), (1, 'ACTIVE'), (2, 'IN_CONTROL'), (3, 'FINISHED')], max_length=10, verbose_name='Название')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_changes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.task', verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'Историй статусов',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщений')),
                ('recipients', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nots', to='core.task', verbose_name='Название задачи')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминаний',
            },
        ),
    ]
